version: 2.1
orbs:
  aws-cli: circleci/aws-cli@0.1.18
jobs:
  build_project:
    working_directory: ~/our-bible-react-app
    docker:
      - image: node:12.14.1
    steps:
      - checkout
      - run: 
          name: Installing dependencies
          command: npm install
      - run: 
          name: Building project
          command: npm run build
      - run: 
          name: Testing project
          command: npm run test
      - persist_to_workspace:
          root: .
          paths:
            - .

  deploy_project:
    executor: aws-cli/default
    steps:
      - attach_workspace:
          at: .
      - aws-cli/setup:
          profile-name: default
      - run:
          name: Upload file to S3
          command: aws s3 sync ./build s3://ourbible.io --acl public-read --delete
      - run:
          name: Set Cloudfront preivew to true
          command: aws configure set preview.cloudfront true
      - run:
          name: Invalidate Cloudfront
          command: aws cloudfront create-invalidation --distribution-id EI9CDNUORQ4U3 --paths "/*"

workflows:
  version: 2
  build:
    jobs:
      - build_project:
          filters:
              branches:
                only:
                  - master
                  - dev
              tags:
                only: /.*/

      - deploy_project:
          requires:
            - build_project
          context: aws-context
          filters:
            branches:
              only: master
            tags:
              only: /.*/
